-- Insert sample offers
INSERT INTO offers (company_name, role_title, location, salary_hourly, tech_stack, experience_rating, review_text, term, job_type, level, work_type, is_verified) VALUES

('Google', 
'Software Engineering Intern', 
'Mountain View, CA', 
58.50, 
ARRAY['Python', 'Go', 'Kubernetes', 'gRPC'], 
5, 
'Amazing experience working on Google Cloud infrastructure. The team was incredibly supportive and I learned so much about distributed systems....', 
'Winter 2025',
'SWE',
'Returning Co-op',
'Hybrid',
true),

('Amazon', 
'Backend Developer Intern', 
'Seattle, WA', 
52.00, 
ARRAY['Java', 'AWS', 'DynamoDB', 'Lambda'], 
4, 
'Great learning opportunity with real impact. Worked on AWS services that handle millions of requests. The oncall rotation was intense but valuable experience.', 
'Summer 2025',
'SWE',
'Returning Co-op',
'Onsite',
true),

('Microsoft', 
'Data Science Intern', 
'Redmond, WA', 
49.00, 
ARRAY['Python', 'R', 'AWS', 'PostgreSQL'], 
4, 
'Good experience overall. Got to work with Azure ML and real customer data. Would have liked more mentorship but the project was interesting.', 
'Fall 2024',
'DS',
'Junior',
'Hybrid',
false),

('Meta', 
'Frontend Developer Intern', 
'Menlo Park, CA', 
55.00, 
ARRAY['React', 'TypeScript', 'GraphQL', 'Jest'], 
3, 
'The tech stack was modern and interesting but the work culture felt very fast-paced and stressful. Lots of meetings and less coding time than expected.', 
'Winter 2025',
'SWE',
'Grad Pipeline',
'Onsite',
false);

